### ISSUE TITLE
[Feat] 영화 정보 및 전체 상영관 정보 조회

### ISSUE THREAD

**Issue by Chan531** [DOSOPT-CDS-WEB-4/CGV-SERVER#5]
## 🛠 Issue

1. 영화 정보 및 전체 상영관 정보 조회 api 관련 업무 
2. schedule, screen 더미 데이터 필요

## 📝 To-do

- [ ] 영화 정보 및 전체 상영관 정보 조회 api 생성
- [ ] 영화 정보 및 전체 상영관 정보 조회 api 명세서 작성
- [ ] schedule, screen 더미 데이터 생성
